/**
 * 美团订单协议规范与默认 Schema 定义 (Meituan Protocol Specification & Presets)
 * 将 150+ 繁杂字段裁剪归纳为 15 个高频业务指标
 */

import type { ChannelProtocolSchema } from '../../types/template';

/** 美团真实订单协议样本数据 (源自生产采集报文) */
export const MEITUAN_RAW_SAMPLE_ORDER = {
  data: {
    address: '自贡市北环路88号',
    agreementHosting: false,
    appointmentStatus: 1110,
    aptCreatTime: 1789443464000,
    aptCreatTimeString: '2026-09-15 11:37:44',
    arriveTime: 1789452000000,
    arriveTimeStr: '2026-09-15 14:00:00',
    autoAccept: 0,
    autoOrderConfirm: 1,
    bizCardCounts: 0,
    bizEnterprisePrice: null,
    bizPromotionDetail: [],
    bizRefund: true,
    bizSmsContact: true,
    blackFlag: '',
    bookSucTime: 1789443490000,
    bookSucTimeString: '2026-09-15 11:38:10',
    booking2CancelDiffTime: 0,
    bookingTime: 1789443464000,
    bookingTimeString: '2026-09-15 11:37:44',
    breakfastInfo: [
      {
        breakfastDate: '2026-09-15 00:00:00',
        breakfastDesc: '不含早',
        paymentUnitId: '3803026324567222330',
      },
    ],
    cancelFee: 0,
    cancelOrder: false,
    cancelRules: [],
    cardCounts: 0,
    cards: [],
    channelLabel: false,
    checkInDate: 1789401600000,
    checkInDateModels: [
      {
        checkInDate: 1789401600000,
        checkInDateString: '2026-09-15 00:00:00',
        pricePerRoom: 26555,
        refundedRoomNightsCnt: 0,
        roomNightsInfo: [
          {
            checkInTimeStamp: 1789401600000,
            checkInTimeStampString: '2026-09-15 00:00:00',
            commission: 2655,
            id: '3803026324567222330',
            mtSoldPrice: 26555,
            refundMoney: 0,
            refundReason: null,
            refunded: false,
            roomType: '',
            roomUser: '',
          },
        ],
      },
    ],
    checkInDateString: '2026-09-15 00:00:00',
    checkInStatus: 4,
    checkInType: 0,
    checkOutDate: 1789488000000,
    checkOutDateString: '2026-09-16 00:00:00',
    commission: 2655,
    commissionDescModel: {
      subRatioDesc: '',
      wxAndLowSub: false,
    },
    contacts: [
      {
        carLicenses: [],
        email: '',
        identity: '',
        name: '巨*',
        phone: '13888889999',
        roomIndex: null,
      },
    ],
    containerStatus: 0,
    continueLiveOrder: false,
    crsPromotionCode: '',
    dawnFlag: 0,
    deliveryOrder: 0,
    departure: null,
    discountType: 0,
    displayedSeparatelyOutsideList: [],
    distributorId: 1,
    donationInfo: {
      charityAmount: 10,
      charityOrder: true,
    },
    dynamicCouponServicePrice: null,
    ebSaveOrder: false,
    enterpriseName: '',
    extensionRoomNum: '',
    extraPrice: -1,
    fixRoom: false,
    floorPrice: 23900,
    freeTip: 0,
    freeTipPrice: 26555,
    fuseInfo: null,
    fxFloorInvoiceInfo: null,
    goodsId: 2532714518,
    goodsInfos: [],
    goodsTagCode: 0,
    goodsType: 1,
    goodsVersion: 1,
    greenChannelMark: 0,
    guaranteeType: 0,
    guests: [
      {
        carLicenses: [],
        email: '',
        identity: '',
        name: '巨*',
        phone: '',
        roomIndex: null,
      },
    ],
    hasKickOutPrice: false,
    hasPromotion: false,
    hourRoomTime: null,
    imMark: 0,
    independentDisplayPrice: [],
    inquiryPrice: false,
    insuranceClaim: 0,
    invDetailModel: null,
    invoiceDisplayInfo: {
      invoiceRequireDesc: '若客人索取发票，请贵酒店开具，参考开票金额：¥265.55',
      showDetail: false,
    },
    invoiceMark: 0,
    invoicePartyTagNewLogic: true,
    invoiceTagModel: {
      invoiceAppointment: 0,
      invoiceCanCreate: true,
      invoiceIsAppointed: false,
      invoiceMoney: 26555,
      invoiceParty: 3,
    },
    isAdvertise: false,
    isCashPayChange: false,
    isOccupiedTransSuc: null,
    keyTags: [],
    kickOutNewPolicyOrder: false,
    kickOutPrice: null,
    longAcceptTimeMark: false,
    lookSensitive: true,
    lowerCarbon: null,
    memberBenefits: 0,
    memberBenefitsWord: [],
    memberCommissionRiskControlMark: 0,
    memberDisplayMode: 1,
    memberLevel: 5,
    memberMark: null,
    modifyGuest: false,
    newOrderId: '',
    nonRoomAddOnPopInfo: null,
    nonRoomOrder: null,
    occupiedMark: 0,
    offLine: 0,
    orderBasePriceModel: {
      amountDetailList: [],
      bizPromotionDetails: [],
      commission: {
        originalPrice: 2655,
        originalPriceLocal: 0,
        price: 2655,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
      floorAwardPrice: null,
      floorPrice: {
        originalPrice: 23900,
        originalPriceLocal: 0,
        price: 23900,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
      kickOutPrice: {
        originalPrice: 0,
        originalPriceLocal: 0,
        price: 0,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
      preSettlementInfo: {
        partnerIncome: '￥238.90',
        refundByMoneyList: [],
        statementPeriod: '2026-09-14 至 2026-09-20',
      },
      promotionPrice: {
        originalPrice: 0,
        originalPriceLocal: 0,
        price: 0,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
      salePrice: {
        originalPrice: 26555,
        originalPriceLocal: 0,
        price: 26555,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
      subRatio: {
        originalPrice: 0,
        originalPriceLocal: 0,
        price: 0,
        priceDesc: '',
        priceLocal: 0,
        showOriginalPrice: false,
      },
    },
    orderContacts: [],
    orderDisplayLabel: '新订',
    orderId: '5035036057245515034',
    orderLabel: 0,
    orderPassAdPrice: null,
    orderPricePattern: 1,
    orderStatusExplain: '',
    orderType: 4,
    originOrRescheduled: 0,
    ownerPhones: [],
    packageBaseInfos: [],
    packageMark: 0,
    packageRoom: 2,
    partnerId: 4551093,
    partnerName: '自贡禅驿酒店有限公司',
    payTime: 1789443465000,
    payTimeString: '2026-09-15 11:37:45',
    paymentType: 0,
    poiId: 1533758592,
    poiIdStr: '1533758592',
    poiName: '禅驿度假酒店（自贡方特恐龙王国店）',
    pointDeductionTip: '',
    preSettlementInfo: {
      partnerIncome: '238.90',
      refundByMoneyList: [],
      statementPeriod: '2026-09-14 至 2026-09-20',
    },
    pretender: false,
    price: 26555,
    rightsModelList: [
      {
        autoConfirmSource: null,
        remindMsg: '',
        rightsCode: 'YCTF',
        rightsConfirmType: '',
        rightsCostDesc: '',
        rightsId: '6000',
        rightsItemModelList: [
          {
            expandDesc: '',
            itemRemindText: '',
            itemText: '可履约（接单后自动确认）',
            itemType: 0,
          },
        ],
        rightsItemStatus: 2,
        rightsName: '延迟退房',
        rightsPerformanceStatus: 1,
        rightsServiceBriefDesc: '',
        rightsServiceDesc: '延迟退房至 14:00，共 1 间',
        rightsServiceDetailDesc: '',
        simpleStatusDesc: '可履约（接单后自动确认）',
      },
    ],
    rightsNames: ['延迟退房'],
    rightsNeedConfirm: 1,
    rightsStatus: 2,
    roomCount: 1,
    roomDesc: '',
    roomId: 993699675,
    roomName: '松香大床房',
    status: 'CONSUMED',
    todayCheckIn: true,
    totalFee: 26555,
    totalOriginFloorPrice: 23900,
    urgent: 0,
    userId: 263280280,
  },
  message: '成功',
  status: 0,
};

/** 美团精炼协议 Schema：将 150+ 字段裁剪精简为 16 个高频核心业务指标 */
export const DEFAULT_MEITUAN_PROTOCOL_SCHEMA: ChannelProtocolSchema = {
  channelId: 'meituan',
  channelCode: 'MEITUAN',
  version: '2026.09',
  updatedAt: '2026-09-16 12:00:00',
  fields: [
    // 1. 基础信息
    {
      key: 'orderNo',
      label: '美团单号',
      path: 'data.orderId',
      category: 'basic',
      transform: 'string',
      sampleValue: '5035036057245515034',
      description: '美团平台订单唯一流水号',
      enabled: true,
      required: true,
    },
    {
      key: 'orderStatus',
      label: '订单状态',
      path: 'data.orderDisplayLabel',
      category: 'basic',
      transform: 'string',
      sampleValue: '新订',
      description: '美团前台展示状态标签',
      enabled: true,
    },
    {
      key: 'orderTime',
      label: '下单时间',
      path: 'data.aptCreatTimeString',
      category: 'basic',
      transform: 'string',
      sampleValue: '2026-09-15 11:37:44',
      description: '客人下单创建时间',
      enabled: true,
    },

    // 2. 酒店房型
    {
      key: 'roomName',
      label: '房型名称',
      path: 'data.roomName',
      category: 'hotel',
      transform: 'string',
      sampleValue: '松香大床房',
      description: '美团售卖房型物理名称',
      enabled: true,
      required: true,
    },
    {
      key: 'roomCount',
      label: '房间间数',
      path: 'data.roomCount',
      category: 'hotel',
      transform: 'string',
      sampleValue: '1',
      description: '本次预订房间数量',
      enabled: true,
    },

    // 3. 入离时间
    {
      key: 'checkInDate',
      label: '入住日期',
      path: 'data.checkInDateString',
      category: 'date',
      transform: 'date',
      sampleValue: '2026-09-15',
      description: '客人登记入住日期',
      enabled: true,
      required: true,
    },
    {
      key: 'checkOutDate',
      label: '离店日期',
      path: 'data.checkOutDateString',
      category: 'date',
      transform: 'date',
      sampleValue: '2026-09-16',
      description: '客人离店退房日期',
      enabled: true,
      required: true,
    },
    {
      key: 'arriveTime',
      label: '预计到店时间',
      path: 'data.arriveTimeStr',
      category: 'date',
      transform: 'string',
      sampleValue: '2026-09-15 14:00:00',
      description: '客人预计抵达酒店时间',
      enabled: true,
    },

    // 4. 住客与联系人
    {
      key: 'guestName',
      label: '入住人',
      path: 'data.guests[*].name',
      category: 'guest',
      transform: 'string',
      sampleValue: '巨*',
      description: '全部入住人姓名 (多住客自动拼接)',
      enabled: true,
    },
    {
      key: 'guestPhone',
      label: '联系电话',
      path: 'data.contacts[*].phone',
      category: 'guest',
      transform: 'maskPhone',
      sampleValue: '138****9999',
      description: '预留联系人手机号',
      enabled: true,
    },

    // 5. 财务结算 (分转元)
    {
      key: 'floorPrice',
      label: '结算底价',
      path: 'data.floorPrice',
      category: 'finance',
      transform: 'centsToYuan',
      sampleValue: '239.00',
      description: '美团与酒店结算底价 (元)',
      enabled: true,
      required: true,
    },
    {
      key: 'salePrice',
      label: 'OTA售价',
      path: 'data.price',
      category: 'finance',
      transform: 'centsToYuan',
      sampleValue: '265.55',
      description: '美团对外销售实收价格 (元)',
      enabled: true,
    },
    {
      key: 'partnerIncome',
      label: '预结算收益',
      path: 'data.orderBasePriceModel.preSettlementInfo.partnerIncome',
      category: 'finance',
      transform: 'string',
      sampleValue: '￥238.90',
      description: '账期预结算预计收入',
      enabled: true,
    },

    // 6. 权益服务
    {
      key: 'breakfast',
      label: '早餐说明',
      path: 'data.breakfastInfo[0].breakfastDesc',
      category: 'rights',
      transform: 'string',
      sampleValue: '不含早',
      description: '套餐是否含早餐说明',
      enabled: true,
    },
    {
      key: 'rightsDesc',
      label: '特色权益',
      path: 'data.rightsModelList[0].rightsServiceDesc',
      category: 'rights',
      transform: 'string',
      sampleValue: '延迟退房至 14:00，共 1 间',
      description: '如延迟退房等会员专享礼遇',
      enabled: true,
    },
    {
      key: 'hasRights',
      label: '是否含权益',
      path: '',
      category: 'rights',
      transform: 'boolean',
      conditionExpr: 'data.rightsModelList.length > 0',
      sampleValue: 'true',
      description: '订单是否包含附加权益',
      enabled: true,
    },

    // 7. 发票信息
    {
      key: 'needInvoice',
      label: '需酒店开票',
      path: '',
      category: 'invoice',
      transform: 'boolean',
      conditionExpr: 'data.invoiceTagModel.invoiceParty == 3',
      sampleValue: 'true',
      description: '美团标记需酒店开具发票',
      enabled: true,
    },
    {
      key: 'invoiceMoney',
      label: '参考开票金额',
      path: 'data.invoiceTagModel.invoiceMoney',
      category: 'invoice',
      transform: 'centsToYuan',
      sampleValue: '265.55',
      description: '开票参考金额 (元)',
      enabled: true,
    },
  ],
};
